apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-kafka-connect
  namespace: paw
  labels:
    team: paw
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1000"
spec:
  image: {{image}}
  port: 8083
  # prometheus:
  #   enabled: true
  #   port: "5556"
  #   path: /metrics
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 3
  liveness:
    path: /
    port: 8083
    initialDelay: 90
    periodSeconds: 10
    failureThreshold: 10
    timeout: 2
  readiness:
    path: /
    port: 8083
    initialDelay: 90
    periodSeconds: 10
    failureThreshold: 10
    timeout: 3
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 125m
      memory: 1536Mi
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: CONNECT_REST_PORT
      value: "8083"
    - name: CONNECT_GROUP_ID
      value: "paw-kafka-connect-group"
    - name: KAFKA_TOPIC_PREFIX
      value: "paw.paw-kafka-connect"
    - name: CONNECT_REST_ADVERTISED_HOST_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  gcp:
    bigQueryDatasets:
      - name: paw_dataprodukter_kafka
        permission: READWRITE
  accessPolicy:
    inbound:
      rules:
        - application: paw-kafka-connect-ui
        - application: paw-kafka-connect-operator
