apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-kafka-connect-ui
  namespace: paw
  labels:
    team: paw
spec:
  image: landoop/kafka-connect-ui:0.9.7
  port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /
    port: 8000
    initialDelay: 120
  ingresses:
    - {{ui.ingress}}
  replicas:
    disableAutoScaling: true
    min: 0
    max: 0
  env:
    - name: CONNECT_URL
      value: http://paw-kafka-connect:8083/
  accessPolicy:
    outbound:
      rules:
        - application: paw-kafka-connect
